# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-08-22 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('buying_price', models.CharField(max_length=128)),
                ('selling_price', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
