# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-08-22 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buying_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
